<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>ConnectionStatistics</name>
    <message>
	<location filename="../connectionstatistics.ui" line="+14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>ListDialog</name>
    <message>
	<location filename="../listdialog.ui" line="+14"/>
        <source>Select your VM</source>
        <translation></translation>
    </message>
    <message>
        <source>Connect</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
	<location filename="../mainwindow.ui" line="+14"/>
        <source>QVD</source>
        <translation></translation>
    </message>
    <message>
        <source>Connect</source>
        <translation></translation>
    </message>
    <message>
        <source>Remember password</source>
        <translation></translation>
    </message>
    <message>
        <source>Restart session</source>
        <translation></translation>
    </message>
    <message>
        <source>Settings</source>
        <translation></translation>
    </message>
    <message>
        <source>Options</source>
        <translation></translation>
    </message>
    <message>
        <source>Enable audio</source>
        <translation></translation>
    </message>
    <message>
        <source>Enable microphone</source>
        <translation></translation>
    </message>
    <message>
        <source>Enable printing</source>
        <translation></translation>
    </message>
    <message>
        <source>Full screen</source>
        <translation></translation>
    </message>
    <message>
        <source>Show bandwidth graph</source>
        <translation></translation>
    </message>
    <message>
        <source>Connectivity</source>
        <translation></translation>
    </message>
    <message>
        <source>Server</source>
        <translation></translation>
    </message>
    <message>
        <source>Connection type</source>
        <translation></translation>
    </message>
    <message>
        <source>Shared Folders</source>
        <translation></translation>
    </message>
    <message>
        <source>Enable shared folders</source>
        <translation></translation>
    </message>
    <message>
        <source>Add</source>
        <translation></translation>
    </message>
    <message>
        <source>Remove</source>
        <translation></translation>
    </message>
    <message>
        <source>Environment Variables</source>
        <translation></translation>
    </message>
    <message>
        <source>USB</source>
        <translation></translation>
    </message>
    <message>
        <source>Enable USB redirection</source>
        <translation></translation>
    </message>
    <message>
        <source>Version</source>
        <translation></translation>
    </message>
    <message>
        <source>Release: (running from source code)
Git commit: N/A
Build: N/A</source>
        <translation></translation>
    </message>
    <message>
        <source>Username</source>
        <translation></translation>
    </message>
    <message>
        <source>Password</source>
        <translation></translation>
    </message>
    <message>
        <source>Second Factor</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;a href=&quot;http://theqvd.com&quot;&gt;© 2022 Qindel Group&lt;/a&gt;</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>SSLErrorDialog</name>
    <message>
	<location filename="../sslerrordialog.ui" line="+14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <source>Problems</source>
        <translation></translation>
    </message>
    <message>
        <source>Result of the certificate check</source>
        <translation></translation>
    </message>
    <message>
        <source>Recommendations</source>
        <translation></translation>
    </message>
    <message>
        <source>Details</source>
        <translation></translation>
    </message>
    <message>
        <source>Accept temporarily</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>TotpEnrollment</name>
    <message>
	<location filename="../totpenrollment.ui" line="+14"/>
        <source>Two factor authentication is required</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Either you or the system administrator enabled two factor authentication for your account.&lt;/p&gt;&lt;p&gt;Please scan the code shown below with your phone using Google Authenticator or a similar tool. Once that is done, enter the code generated by the app into t he &amp;quot;Second Factor&amp;quot; field. You can also enter the code below into your application by hand.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;If you are having trouble logging in, the server&apos;s owner provided the following message:&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>(no message has been set)</source>
        <translation></translation>
    </message>
</context>
</TS>
