#!/bin/bash

docker build . -t ubuntu-devtools:21.04-0
docker run --name qvd-build-ubuntu-21.04 -it --security-opt seccomp=unconfined ubuntu-devtools:21.04-0 /build
[ $? -eq 0 ] && docker commit qvd-build-ubuntu-21.04 ubuntu-devtools:21.04-0 && docker rm qvd-build-ubuntu-21.04
