Document: qvd-client-qt
Title: Debian qvd-client-qt Manual
Author: <insert document author here>
Abstract: This manual describes what qvd-client-qt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qvd-client-qt/qvd-client-qt.sgml.gz

Format: postscript
Files: /usr/share/doc/qvd-client-qt/qvd-client-qt.ps.gz

Format: text
Files: /usr/share/doc/qvd-client-qt/qvd-client-qt.text.gz

Format: HTML
Index: /usr/share/doc/qvd-client-qt/html/index.html
Files: /usr/share/doc/qvd-client-qt/html/*.html
