#!/bin/bash


tar=`../make_tar`
tar_filename=`basename "$tar"`
tar_dir=`basename "$tar" .orig.tar.xz | sed 's/qt_/qt-/'`



[ -d "/tmp/sles-files" ] && rm -rf /tmp/sles-files
mkdir -p /tmp/sles-files
cp -Rdpv files/rpm/*  /tmp/sles-files/
cp -Rdpv $tar         /tmp/sles-files/

curdir=`pwd`
docker run -it -v /tmp/sles-files:/files:Z -v $curdir/output/sles:/out qvd-build-sles:15sp2 /files/build_nx
