#!/bin/bash

tar=`../make_tar`
tar_filename=`basename "$tar"`
tar_dir=`basename "$tar" .orig.tar.xz | sed 's/qt_/qt-/'`

[ -d "/tmp/centos-files" ] && rm -rf /tmp/centos-files
mkdir -p /tmp/centos-files
cp -Rpv files/rpm/*  /tmp/centos-files/
cp -Rpv "$tar"       /tmp/centos-files/

BUILD_NX=$1

if [ "$BUILD_NX" == "{true}" ] ; then

   [ -d "$curdir/output/centos_nx-libs" ] && rm -rf $curdir/output/centos_nx-libs
   mkdir -p $curdir/output/centos_nx-libs
   docker_image=`docker images -q nx-libs:centos8`

   if [ -z "$docker_image" ] ; then
      cd docker/centos-8/nx-libs
      docker build . -t nx-libs:centos8 
      cd $curdir
      docker run -i --privileged -u nxbuilder -v $curdir/output/centos_nx-libs:/out nx-libs:centos8 /build.sh
   else
     docker run -i --privileged -u nxbuilder -v $curdir/output/centos_nx-libs:/out nx-libs:centos8 /build.sh
   fi

fi

curdir=`pwd`

docker_image=`docker images -q qvd-build-centos:8`

if [ -z "$docker_image" ] ; then
   cd docker/centos-8
   bash -x build
   cd "$curdir"
   docker run -i -v /tmp/centos-files:/files:Z -v $curdir/output/centos8:/out qvd-build-centos:8 /files/build_nx
else
   docker run -i -v /tmp/centos-files:/files:Z -v $curdir/output/centos8:/out qvd-build-centos:8 /files/build_nx
fi
