#!/bin/bash


tar=`../make_tar`
tar_filename=`basename "$tar"`
tar_dir=`basename "$tar" .orig.tar.xz | sed 's/qt_/qt-/'`



[ -d "/tmp/centos-files" ] && rm -rf /tmp/centos-files
mkdir -p /tmp/centos-files
cp -Rdpv files/rpm/*  /tmp/centos-files/
cp -Rdpv $tar         /tmp/centos-files/

curdir=`pwd`
podman run -it -v /tmp/centos-files:/files:Z -v $curdir/output/centos8:/out qvd-build-centos:8 /files/build_nx
